services:
  taskosaur:
    build:
      context: .
      dockerfile: taskosaur/Dockerfile.prod
    ports:
      - "${APP_PORT:-9100}:${APP_PORT:-9100}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APP_PORT=${APP_PORT:-9100}
      - BE_DATABASE_URL=${BE_DATABASE_URL:-postgresql://user:password@host.docker.internal:5432/taskosaur}
      - BE_REDIS_HOST=${BE_REDIS_HOST:-redis}
      - BE_REDIS_PORT=${BE_REDIS_PORT:-6379}
      - BE_REDIS_PASSWORD=${BE_REDIS_PASSWORD:-}
      - BE_SMTP_HOST=${BE_SMTP_HOST:-localhost}
      - BE_SMTP_PORT=${BE_SMTP_PORT:-587}
      - BE_JWT_SECRET=${BE_JWT_SECRET:-your-jwt-secret-key-change-this}
      - BE_JWT_REFRESH_SECRET=${BE_JWT_REFRESH_SECRET:-your-refresh-secret-key-change-this-too}
      - BE_JWT_EXPIRES_IN=${BE_JWT_EXPIRES_IN:-15m}
      - BE_JWT_REFRESH_EXPIRES_IN=${BE_JWT_REFRESH_EXPIRES_IN:-7d}
      - BE_SMTP_USER=${BE_SMTP_USER:-}
      - BE_SMTP_PASS=${BE_SMTP_PASS:-}
      - BE_SMTP_FROM=${BE_SMTP_FROM:-noreply@taskosaur.com}
      - BE_UPLOAD_DEST=${BE_UPLOAD_DEST:-./uploads}
      - BE_MAX_FILE_SIZE=${BE_MAX_FILE_SIZE:-10485760}
      - BE_MAX_CONCURRENT_JOBS=${BE_MAX_CONCURRENT_JOBS:-5}
      - BE_JOB_RETRY_ATTEMPTS=${BE_JOB_RETRY_ATTEMPTS:-3}
    extra_hosts:
      - "host.docker.internal:host-gateway"
